import { ICurrencyInfo } from './currency.type';

export const DEFAULT_VALUE_ZERO = 0;

export const SUPPORTED_CURRENCIES: ICurrencyInfo[] = [
  {
    code: 'USD',
    name: 'US Dollar',
    origin: 'United States',
    flag: 'https://flagcdn.com/w40/us.png',
  },
  {
    code: 'EUR',
    name: 'Euro',
    origin: 'European Union',
    flag: 'https://flagcdn.com/w40/eu.png',
  },
  {
    code: 'GBP',
    name: 'British Pound',
    origin: 'United Kingdom',
    flag: 'https://flagcdn.com/w40/gb.png',
  },
  {
    code: 'JPY',
    name: 'Japanese Yen',
    origin: 'Japan',
    flag: 'https://flagcdn.com/w40/jp.png',
  },
  {
    code: 'INR',
    name: 'Indian Rupee',
    origin: 'India',
    flag: 'https://flagcdn.com/w40/in.png',
  },
  {
    code: 'AUD',
    name: 'Australian Dollar',
    origin: 'Australia',
    flag: 'https://flagcdn.com/w40/au.png',
  },
  {
    code: 'CAD',
    name: 'Canadian Dollar',
    origin: 'Canada',
    flag: 'https://flagcdn.com/w40/ca.png',
  },
  {
    code: 'CHF',
    name: 'Swiss Franc',
    origin: 'Switzerland',
    flag: 'https://flagcdn.com/w40/ch.png',
  },
  {
    code: 'CNY',
    name: 'Chinese Yuan',
    origin: 'China',
    flag: 'https://flagcdn.com/w40/cn.png',
  },
  {
    code: 'SEK',
    name: 'Swedish Krona',
    origin: 'Sweden',
    flag: 'https://flagcdn.com/w40/se.png',
  },
  {
    code: 'NZD',
    name: 'New Zealand Dollar',
    origin: 'New Zealand',
    flag: 'https://flagcdn.com/w40/nz.png',
  },
  {
    code: 'MXN',
    name: 'Mexican Peso',
    origin: 'Mexico',
    flag: 'https://flagcdn.com/w40/mx.png',
  },
  {
    code: 'SGD',
    name: 'Singapore Dollar',
    origin: 'Singapore',
    flag: 'https://flagcdn.com/w40/sg.png',
  },
  {
    code: 'HKD',
    name: 'Hong Kong Dollar',
    origin: 'Hong Kong',
    flag: 'https://flagcdn.com/w40/hk.png',
  },
  {
    code: 'NOK',
    name: 'Norwegian Krone',
    origin: 'Norway',
    flag: 'https://flagcdn.com/w40/no.png',
  },
  {
    code: 'KRW',
    name: 'South Korean Won',
    origin: 'South Korea',
    flag: 'https://flagcdn.com/w40/kr.png',
  },
  {
    code: 'TRY',
    name: 'Turkish Lira',
    origin: 'Turkey',
    flag: 'https://flagcdn.com/w40/tr.png',
  },
  {
    code: 'RUB',
    name: 'Russian Ruble',
    origin: 'Russia',
    flag: 'https://flagcdn.com/w40/ru.png',
  },
  {
    code: 'BRL',
    name: 'Brazilian Real',
    origin: 'Brazil',
    flag: 'https://flagcdn.com/w40/br.png',
  },
  {
    code: 'ZAR',
    name: 'South African Rand',
    origin: 'South Africa',
    flag: 'https://flagcdn.com/w40/za.png',
  },
  {
    code: 'DKK',
    name: 'Danish Krone',
    origin: 'Denmark',
    flag: 'https://flagcdn.com/w40/dk.png',
  },
  {
    code: 'PLN',
    name: 'Polish Zloty',
    origin: 'Poland',
    flag: 'https://flagcdn.com/w40/pl.png',
  },
  {
    code: 'THB',
    name: 'Thai Baht',
    origin: 'Thailand',
    flag: 'https://flagcdn.com/w40/th.png',
  },
  {
    code: 'IDR',
    name: 'Indonesian Rupiah',
    origin: 'Indonesia',
    flag: 'https://flagcdn.com/w40/id.png',
  },
  {
    code: 'HUF',
    name: 'Hungarian Forint',
    origin: 'Hungary',
    flag: 'https://flagcdn.com/w40/hu.png',
  },
  {
    code: 'CZK',
    name: 'Czech Koruna',
    origin: 'Czech Republic',
    flag: 'https://flagcdn.com/w40/cz.png',
  },
  {
    code: 'ILS',
    name: 'Israeli Shekel',
    origin: 'Israel',
    flag: 'https://flagcdn.com/w40/il.png',
  },
  {
    code: 'CLP',
    name: 'Chilean Peso',
    origin: 'Chile',
    flag: 'https://flagcdn.com/w40/cl.png',
  },
  {
    code: 'PHP',
    name: 'Philippine Peso',
    origin: 'Philippines',
    flag: 'https://flagcdn.com/w40/ph.png',
  },
  {
    code: 'AED',
    name: 'UAE Dirham',
    origin: 'United Arab Emirates',
    flag: 'https://flagcdn.com/w40/ae.png',
  },
  {
    code: 'COP',
    name: 'Colombian Peso',
    origin: 'Colombia',
    flag: 'https://flagcdn.com/w40/co.png',
  },
  {
    code: 'SAR',
    name: 'Saudi Riyal',
    origin: 'Saudi Arabia',
    flag: 'https://flagcdn.com/w40/sa.png',
  },
  {
    code: 'MYR',
    name: 'Malaysian Ringgit',
    origin: 'Malaysia',
    flag: 'https://flagcdn.com/w40/my.png',
  },
  {
    code: 'RON',
    name: 'Romanian Leu',
    origin: 'Romania',
    flag: 'https://flagcdn.com/w40/ro.png',
  },
];
